# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='url',
        ),
    ]
