# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_remove_database_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
