# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_auto_20160415_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
