# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0005_database_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
