# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0006_database_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newinternship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('newintern', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
