# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0007_newinternship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimage',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
